### ISSUE TITLE
How to put execution results in a variable？ like top?

### ISSUE THREAD

**Issue by Mountains-and-rivers** [kr/pty#73]
![14_06_16__03_29_2019](https://user-images.githubusercontent.com/15889219/55212795-1112e380-522c-11e9-8c3f-c86e46b0e30f.jpg)

this is not what i want ,i did below:

![10_32_23__03_29_2019](https://user-images.githubusercontent.com/15889219/55212796-13753d80-522c-11e9-942e-7fa3dd3838ce.jpg)

but ,'ls' and '\n'  is not what i want.  if i write 'top', i need put results in a variable real time。

it lookes like a event which can  monitor execution results。

can you help me？

**Comment by Mountains-and-rivers** [comment]
The result should keep the style of the linux terminal。

**Comment by creack** [comment]
In order to execute `top` in a tty and get the result stream a variable, you can simply use `pty.Start` like this:

```go
package main

import (
        "os/exec"

        "github.com/kr/pty"
)

func main() {
        c := exec.Command("top")
        tty, _ := pty.Start(c)
}
```

`tty` will contain `top`'s output stream.

If you want to record it for a given time and print it, you can consume the stream into a buffer.

Example:

```go
package main

import (
        "bytes"
        "io"
        "os"
        "os/exec"
        "time"

        "github.com/kr/pty"
)

func main() {
        // Start the command in a tty.
        c := exec.Command("top")
        tty, _ := pty.Start(c)

        // Consume the stream for 2 seconds.
        buf := bytes.NewBuffer(nil)
        go func() {
                <-time.After(2 * time.Second)
                c.Process.Kill()
        }()
        io.Copy(buf, tty)

        // Print the result.
        io.Copy(os.Stdout, buf)
}
```

Closing at it is outside the scope of this lib. I'd recommend to try the Golang's group: https://groups.google.com/forum/#!forum/golang-nuts
