### ISSUE TITLE
i want to create a stream instead of socket connection? but i failed, Is this feasible?

### ISSUE THREAD

**Issue by Mountains-and-rivers** [kr/pty#74]
### 
```
package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/kr/pty"
)

func main() {

	c := exec.Command("/bin/bash", "-l")
	c.Env = append(os.Environ(), "TERM=xterm")
	tty, _ := pty.Start(c)
	sr := strings.NewReader("ls\n")

	ch := make(chan int, 0)

	go func() {
		for {
			read, _ := io.Copy(tty, sr)
			if read > 0 {
				ch <- 1
				fmt.Println("1111111111111111111111111")
				break
			}
		}
	}()

	go func() {
		for {
			select {
			case <-ch:
				time.Sleep(1 * time.Second)
				buf := make([]byte, 1024)
				tty.Read(buf)
				fmt.Println("22222222222222222222222222")
				fmt.Println(string(buf))
			case <-time.After(2 * time.Second):
				continue
			}
		}

	}()

	for {

	}
}


```

**Comment by Mountains-and-rivers** [comment]
if i do like this 	```sr := strings.NewReader("top\n")；```  then there is no output？ why ？ i need your help？

**Comment by creack** [comment]
TTYs are devices and are binary in nature. In you code, here, you interrupt the data with `\n` using `fmt.Println`. It is also not a good idea to convert binary to string, keep in mind that the tty is not just text, but also the line discipline, term caps & all.

The reason the sample code works with `ls` but not `top` is because you read only once per command. `top` is a long running process with a continuous dynamic output, so you'll need to continuously read the ouput if you want it to work.

It won't be a great, but in order to get the full output from `top`, you can simply replace `ch <- 1` by `close(ch)` so the read loop will not wait until the next command to read.

Closing as it is outside the scope of this lib.
